### ISSUE TITLE
Failed to load response

### ISSUE THREAD

**Issue by Bolaji06** [Vidhanvyrs/WeatherApp#8]
Was unable to load the location and the weather details when trying to search for a weather details of a particular location.

**Comment by Bolaji06** [comment]
> Was unable to load the location and the weather details when trying to search for a weather details of a particular location.
<img width="890" alt="Screenshot 2023-08-13 204836" src="https://github.com/Vidhanvyrs/WeatherApp/assets/40664855/514cd82b-0862-4455-893c-ba77ef1c84a9">

**Comment by Vidhanvyrs** [comment]
well the problem is coming due to vercel as vercel only  hosts static website so we are here unable to fetch the weather details and use the map 
if you fork and run the project locally you will not have this load issue 
Actually i am working on it to host it properly so that the site runs fully functional

**Comment by Bolaji06** [comment]
I don't think the problem is from the hosting service...Think is from the code itself

**Comment by Bolaji06** [comment]
> I don't think the problem is from the hosting service...Think is from the code itself

I can quickly resolve the issue if assigned

**Comment by Vidhanvyrs** [comment]
Okay so can you be able to resolve it

**Comment by Bolaji06** [comment]
> Okay so can you be able to resolve it

Yeah

**Comment by Vidhanvyrs** [comment]
fine I am assigning you this issue 
thanx for filing it

**Comment by Vidhanvyrs** [comment]
so yeah i got to see these errors here
![image](https://github.com/Vidhanvyrs/WeatherApp/assets/94836010/d455b401-be7b-4701-9791-b5bf6bcac6f6)

**Comment by Vidhanvyrs** [comment]
so on having a look around in the code i think the problem lies in 
 const url = `http://api.openweathermap.org/geo/1.0/direct?q=${location}&limit=5&appid=50c7eef00d13b49fb4b8a0b1dbaceafb`;
 as here we are using http instead the error is not fetching the details due to security reasons so http should be changed to https 
 If this resolves the issue then let me know and send the PR I'll merge it

**Comment by Bolaji06** [comment]
Just sent a PR you can review it now
